// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euwgryvtmtjbubhqtmxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1d2dyeXZ0bXRqYnViaHF0bXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDkwMTIsImV4cCI6MjA2MzIyNTAxMn0.EZMb09Me-VCnjjx2HFHppbgnUm-U-qq3Yxh0J-uajyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);